apiVersion: v1
kind: Service
metadata:
  name: mediawiki-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30283
  selector:
    app: mediawiki-frontend
