apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: my-data-mediawiki
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500M
