replicaCount: 1
mysql:
  name: mysql
  container:
    image: mysql:5.6
    port: 3306
    env:
    - name: MYSQL_DATABASE
      value: mediawiki
    - name: MYSQL_USER
      value: app
    - name: MYSQL_PASSWORD
      value: secure
    - name: MYSQL_ROOT_PASSWORD
      value: secure
    service:
      type: ClusterIP
      port: 3306
