apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  labels:
    app: {{ .Values.mysql.label }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.label }}
    spec:
      volumes:
        - name: {{ .Values.mysql.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.volume.pvc.name }}
      containers:
        - name: {{ .Values.mysql.name }}
          image: {{ .Values.mysql.container.image }}  
          ports:
            - containerPort: {{ .Values.mysql.container.port }}
          volumeMounts:             
            - name: {{ .Values.mysql.volume.name }}
              mountPath: {{ .Values.mysql.volume.mountpath }} 
