apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
spec:
  type: {{ .Values.mysql.service.type }}
  selector:             
    app: {{ .Values.mysql.name }}
  ports:
    - port: {{ .Values.mysql.service.port }}       
      targetPort: {{ .Values.mysql.service.targetport }}
  clusterIP: None
