apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
spec:
  type: {{ .Values.mysql.service.type }}
  selector:             
    app: {{ .Values.mysql.label }}
  ports:
    - port: {{ .Values.mysql.service.port }}       
  clusterIP: None
