apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mediawiki.name }}
spec:
  type: {{ .Values.mediawiki.service.type }}
  selector:             
    app: {{ .Values.mediawiki.label }}
  ports:
    - port: {{ .Values.mediawiki.service.port }}       
      targetPort: {{ .Values.mediawiki.service.targetport }}
      nodePort: {{ .Values.mediawiki.service.nodeport }}

