apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mediawiki.name }}
  labels:
    app: {{ .Values.mediawiki.name }}
spec:
  replicas: {{ .Values.mediawiki.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mediawiki.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mediawiki.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.mediawiki.name }}
      initContainers:
      - name: init-wait
        image: alpine
        command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 sqldb 3306 && exit 0 || sleep 3; done; exit 1"]

      containers:
        - name: {{ .Values.mediawiki.name }}
          image: {{ .Values.mediawiki.container.image }}  
          ports:
            - containerPort: {{ .Values.mediawiki.container.port }}
          env:
            {{- range .Values.mediawiki.container.env}}
            - name: {{ .key}}
              value: {{ .value}}
            {{- end}}
          volumeMounts:
          - name: {{ .Values.mediawiki.container.volumemounts.name }}
            mountPath: {{ .Values.mediawiki.container.volumemounts.mountpath }}
      volumes:
      - name: {{ .Values.mediawiki.container.volumemounts.name }}
        persistentVolumeClaim:
           claimName: {{ .Values.spec.spec.volumes.pvc.claimname }}
 
